### ISSUE TITLE
slc arc only working in Safari on OSX

### ISSUE THREAD

**Issue by arcreative** [strongloop/strong-arc#1442] opened 2015-07-10 16:20 UTC
Chrome console output:

```
Download the React DevTools for a better development experience: http://fb.me/react-devtools
angular.js:11655 Call segmentio API with pageview ["/"]
angular.js:11655 Segmentio API not yet initialized, queueing call
6angular.js:11655 SyntaxError: Unexpected token b
    at Object.parse (native)
    at Object.fromJson (http://localhost:4800/scripts/vendor/angular/angular.js:1072:14)
    at Object.angular.module.factory.factory.get (http://localhost:4800/scripts/vendor/angular-cookies/angular-cookies.js:172:34)
    at request (http://localhost:4800/scripts/modules/arc/arc.module.js:275:31)
    at processQueue (http://localhost:4800/scripts/vendor/angular/angular.js:13248:27)
    at http://localhost:4800/scripts/vendor/angular/angular.js:13264:27
    at Scope.$get.Scope.$eval (http://localhost:4800/scripts/vendor/angular/angular.js:14466:28)
    at Scope.$get.Scope.$digest (http://localhost:4800/scripts/vendor/angular/angular.js:14282:31)
    at Scope.$get.Scope.$apply (http://localhost:4800/scripts/vendor/angular/angular.js:14571:24)
    at bootstrapApply (http://localhost:4800/scripts/vendor/angular/angular.js:1455:15)(anonymous function) @ angular.js:11655$get @ angular.js:8596processQueue @ angular.js:13256(anonymous function) @ angular.js:13264$get.Scope.$eval @ angular.js:14466$get.Scope.$digest @ angular.js:14282$get.Scope.$apply @ angular.js:14571bootstrapApply @ angular.js:1455invoke @ angular.js:4203doBootstrap @ angular.js:1453bootstrap @ angular.js:1473angularInit @ angular.js:1367(anonymous function) @ angular.js:26304jQuery.Callbacks.fire @ jquery.js:3099jQuery.Callbacks.self.fireWith @ jquery.js:3211jQuery.extend.ready @ jquery.js:3417completed @ jquery.js:3433
angular.js:11655 Error: [$compile:tpload] Failed to load template: ./scripts/modules/landing/templates/landing.app.selector.html
http://errors.angularjs.org/1.3.15/$compile/tpload?p0=.%2Fscripts%2Fmodules%2Flanding%2Ftemplates%2Flanding.app.selector.html
    at REGEX_STRING_REGEXP (angular.js:63)
    at handleError (angular.js:16133)
    at processQueue (angular.js:13248)
    at angular.js:13264
    at Scope.$get.Scope.$eval (angular.js:14466)
    at Scope.$get.Scope.$digest (angular.js:14282)
    at Scope.$get.Scope.$apply (angular.js:14571)
    at bootstrapApply (angular.js:1455)
    at Object.invoke (angular.js:4203)
    at doBootstrap (angular.js:1453)(anonymous function) @ angular.js:11655$get @ angular.js:8596processQueue @ angular.js:13256(anonymous function) @ angular.js:13264$get.Scope.$eval @ angular.js:14466$get.Scope.$digest @ angular.js:14282$get.Scope.$apply @ angular.js:14571bootstrapApply @ angular.js:1455invoke @ angular.js:4203doBootstrap @ angular.js:1453bootstrap @ angular.js:1473angularInit @ angular.js:1367(anonymous function) @ angular.js:26304jQuery.Callbacks.fire @ jquery.js:3099jQuery.Callbacks.self.fireWith @ jquery.js:3211jQuery.extend.ready @ jquery.js:3417completed @ jquery.js:3433
angular.js:11655 Error: [$compile:tpload] Failed to load template: ./scripts/modules/pm/templates/pm.app.controller.menu.html
http://errors.angularjs.org/1.3.15/$compile/tpload?p0=.%2Fscripts%2Fmodules%2Fpm%2Ftemplates%2Fpm.app.controller.menu.html
    at REGEX_STRING_REGEXP (angular.js:63)
    at handleError (angular.js:16133)
    at processQueue (angular.js:13248)
    at angular.js:13264
    at Scope.$get.Scope.$eval (angular.js:14466)
    at Scope.$get.Scope.$digest (angular.js:14282)
    at Scope.$get.Scope.$apply (angular.js:14571)
    at bootstrapApply (angular.js:1455)
    at Object.invoke (angular.js:4203)
    at doBootstrap (angular.js:1453)(anonymous function) @ angular.js:11655$get @ angular.js:8596processQueue @ angular.js:13256(anonymous function) @ angular.js:13264$get.Scope.$eval @ angular.js:14466$get.Scope.$digest @ angular.js:14282$get.Scope.$apply @ angular.js:14571bootstrapApply @ angular.js:1455invoke @ angular.js:4203doBootstrap @ angular.js:1453bootstrap @ angular.js:1473angularInit @ angular.js:1367(anonymous function) @ angular.js:26304jQuery.Callbacks.fire @ jquery.js:3099jQuery.Callbacks.self.fireWith @ jquery.js:3211jQuery.extend.ready @ jquery.js:3417completed @ jquery.js:3433
angular.js:11655 Error: [$compile:tpload] Failed to load template: ./scripts/modules/common/templates/common.popover.help.html
http://errors.angularjs.org/1.3.15/$compile/tpload?p0=.%2Fscripts%2Fmodules%2Fcommon%2Ftemplates%2Fcommon.popover.help.html
    at REGEX_STRING_REGEXP (angular.js:63)
    at handleError (angular.js:16133)
    at processQueue (angular.js:13248)
    at angular.js:13264
    at Scope.$get.Scope.$eval (angular.js:14466)
    at Scope.$get.Scope.$digest (angular.js:14282)
    at Scope.$get.Scope.$apply (angular.js:14571)
    at bootstrapApply (angular.js:1455)
    at Object.invoke (angular.js:4203)
    at doBootstrap (angular.js:1453)(anonymous function) @ angular.js:11655$get @ angular.js:8596processQueue @ angular.js:13256(anonymous function) @ angular.js:13264$get.Scope.$eval @ angular.js:14466$get.Scope.$digest @ angular.js:14282$get.Scope.$apply @ angular.js:14571bootstrapApply @ angular.js:1455invoke @ angular.js:4203doBootstrap @ angular.js:1453bootstrap @ angular.js:1473angularInit @ angular.js:1367(anonymous function) @ angular.js:26304jQuery.Callbacks.fire @ jquery.js:3099jQuery.Callbacks.self.fireWith @ jquery.js:3211jQuery.extend.ready @ jquery.js:3417completed @ jquery.js:3433
angular.js:11655 Error: [$compile:tpload] Failed to load template: ./scripts/modules/common/templates/common.message.global.html
http://errors.angularjs.org/1.3.15/$compile/tpload?p0=.%2Fscripts%2Fmodules%2Fcommon%2Ftemplates%2Fcommon.message.global.html
    at REGEX_STRING_REGEXP (angular.js:63)
    at handleError (angular.js:16133)
    at processQueue (angular.js:13248)
    at angular.js:13264
    at Scope.$get.Scope.$eval (angular.js:14466)
    at Scope.$get.Scope.$digest (angular.js:14282)
    at Scope.$get.Scope.$apply (angular.js:14571)
    at bootstrapApply (angular.js:1455)
    at Object.invoke (angular.js:4203)
    at doBootstrap (angular.js:1453)(anonymous function) @ angular.js:11655$get @ angular.js:8596processQueue @ angular.js:13256(anonymous function) @ angular.js:13264$get.Scope.$eval @ angular.js:14466$get.Scope.$digest @ angular.js:14282$get.Scope.$apply @ angular.js:14571bootstrapApply @ angular.js:1455invoke @ angular.js:4203doBootstrap @ angular.js:1453bootstrap @ angular.js:1473angularInit @ angular.js:1367(anonymous function) @ angular.js:26304jQuery.Callbacks.fire @ jquery.js:3099jQuery.Callbacks.self.fireWith @ jquery.js:3211jQuery.extend.ready @ jquery.js:3417completed @ jquery.js:3433
angular.js:11655 Cannot get project's package definition. SyntaxError: Unexpected token b
    at Object.parse (native)
    at Object.fromJson (http://localhost:4800/scripts/vendor/angular/angular.js:1072:14)
    at Object.angular.module.factory.factory.get (http://localhost:4800/scripts/vendor/angular-cookies/angular-cookies.js:172:34)
    at request (http://localhost:4800/scripts/modules/arc/arc.module.js:275:31)
    at processQueue (http://localhost:4800/scripts/vendor/angular/angular.js:13248:27)
    at http://localhost:4800/scripts/vendor/angular/angular.js:13264:27
    at Scope.$get.Scope.$eval (http://localhost:4800/scripts/vendor/angular/angular.js:14466:28)
    at Scope.$get.Scope.$digest (http://localhost:4800/scripts/vendor/angular/angular.js:14282:31)
    at Scope.$get.Scope.$apply (http://localhost:4800/scripts/vendor/angular/angular.js:14571:24)
    at bootstrapApply (http://localhost:4800/scripts/vendor/angular/angular.js:1455:15)
angular.js:11655 Cannot get project's package definition. SyntaxError: Unexpected token b
    at Object.parse (native)
    at Object.fromJson (http://localhost:4800/scripts/vendor/angular/angular.js:1072:14)
    at Object.angular.module.factory.factory.get (http://localhost:4800/scripts/vendor/angular-cookies/angular-cookies.js:172:34)
    at request (http://localhost:4800/scripts/modules/arc/arc.module.js:275:31)
    at processQueue (http://localhost:4800/scripts/vendor/angular/angular.js:13248:27)
    at http://localhost:4800/scripts/vendor/angular/angular.js:13264:27
    at Scope.$get.Scope.$eval (http://localhost:4800/scripts/vendor/angular/angular.js:14466:28)
    at Scope.$get.Scope.$digest (http://localhost:4800/scripts/vendor/angular/angular.js:14282:31)
    at Scope.$get.Scope.$apply (http://localhost:4800/scripts/vendor/angular/angular.js:14571:24)
    at bootstrapApply (http://localhost:4800/scripts/vendor/angular/angular.js:1455:15)
2angular.js:11655 SyntaxError: Unexpected token b
    at Object.parse (native)
    at Object.fromJson (http://localhost:4800/scripts/vendor/angular/angular.js:1072:14)
    at Object.angular.module.factory.factory.get (http://localhost:4800/scripts/vendor/angular-cookies/angular-cookies.js:172:34)
    at request (http://localhost:4800/scripts/modules/arc/arc.module.js:275:31)
    at processQueue (http://localhost:4800/scripts/vendor/angular/angular.js:13248:27)
    at http://localhost:4800/scripts/vendor/angular/angular.js:13264:27
    at Scope.$get.Scope.$eval (http://localhost:4800/scripts/vendor/angular/angular.js:14466:28)
    at Scope.$get.Scope.$digest (http://localhost:4800/scripts/vendor/angular/angular.js:14282:31)
    at Scope.$get.Scope.$apply (http://localhost:4800/scripts/vendor/angular/angular.js:14571:24)
    at bootstrapApply (http://localhost:4800/scripts/vendor/angular/angular.js:1455:15)
```

I've installed fresh versions of everything (with `npm cache clean`) on node `0.12.6`.  Help?

**Comment by crandmck** [comment] 2015-07-21 04:46
What OS?

**Comment by arcreative** [comment] 2015-07-21 04:52
Yosemite

**Comment by crandmck** [comment] 2015-07-21 16:38
I am unable to reproduce with Chrome 43.0.2357.132 on Yosemite with StrongLoop v4.0.5 (node v0.12.6).

**Comment by sam-github** [comment] 2015-07-21 18:32
@arcreative can you make sure you are completely up to date `npm install -g strongloop`, and confirm?

Also, can you try in a new app? And what do you mean by "not work"? Did arc UI load? Did you try to do something specific? At what point does it "not work"?

**Comment by cgole** [comment] 2015-11-12 22:27
Dont think this is still an issue. We have tried on different browsers

**Comment by cgole** [comment] 2015-11-12 22:42
closing this for now. Please, reopen if necessary

**Closed by cgole** 2015-11-12 22:42 UTC
Labels: bug
