### ISSUE TITLE
Composer bug: plural display for model name is incorrect

### ISSUE THREAD

**Issue by seanbrookes** [strongloop/strong-arc#1108] opened 2015-03-27 05:07 UTC
when you create a new model it should automatically display the plural of the model name but it shows the model name without being pluralized.

**Comment by cebor** [comment] 2015-05-13 07:24
same issue here.

**Comment by anthonyettinger** [comment] 2015-11-03 00:07
Duplicate of #1310

**Closed** 2015-11-03 00:15 UTC
Labels: #plan, bug, UX
