### ISSUE TITLE
slc loopback doesn't create a .gitignore file, or offer to git init the repo

### ISSUE THREAD

**Issue by sam-github** [strongloop/strong-arc#685] opened 2014-12-10 18:16 UTC
I'm trying to put my app under version control, to see what arc does, lack of .gitignore makes it harder than necessary.

Why didn't loopback offer to git init my repo and commit the initial scaffolding for me?

**Comment by raymondfeng** [comment] 2015-01-05 23:06
I'm fine to add .gitignore. But offering `git init` might be too much as not all developers have `git` installed.

**Comment by sam-github** [comment] 2015-01-05 23:50
git init would have to be optional, if it existed, but I'm happy with just adding a .gitignore.

It makes it possible to paste `git init; git add .; git ci -m "Initial commit"` into a console and be up and running.

**Comment by bajtos** [comment] 2015-01-06 07:05
+1 for adding .gitignore

**Comment by sam-github** [comment] 2015-01-07 00:28
I can't think of anything except

```
node_modules
npm-debug.log
.strong-pm
````

that should be in the .gitignore, unless there is some known test ephemera, but I don't think LB scaffolds tests that output to the fs.

**Comment by bajtos** [comment] 2015-01-07 07:36
The following entries are usually added too:

```
.idea
.project
.DS_Store
*.pid
*.swp
*.swo
*.iml
*.tgz
```

That way artefacts like editor config/temp files don't end up published to npmjs.org.

**Comment by bajtos** [comment] 2015-01-07 07:43
Actually, there is already a .gitignore file in the template (see https://github.com/strongloop/loopback-workspace/blob/master/templates/components/api-server/template/.gitignore).

I suspect the problem is either in `ncp` used by [Workspace.copyRecursive](https://github.com/strongloop/loopback-workspace/blob/5881e655bbcf62df81e48916f4f46f501fad6c62/models/workspace.js#L64) or yeoman's [this.directory](http://yeoman.github.io/generator/actions.html#directory) which we inject in [generator-loopback:app](https://github.com/strongloop/generator-loopback/blob/b5069c59c71b2e5aa046b23a583c1b4752235c4e/app/index.js#L47-L50). How does `this.directory` handle dot files? Related reading: http://yeoman.io/authoring/file-system.html

Since this is a reasonably easy task, I am assigning it to @superkhau as a learning exercise. 

@superkhau Please do speak up if you disagree.

**Comment by superkhau** [comment] 2015-02-04 08:27
@bajtos `ncp` does not copy hidden files. See https://github.com/AvianFlu/ncp/issues/27

Should I just manually add code to copy the .gitignore and add a comment referencing the issue? ie)

```
fs.createReadStream('path/to/src/.gitignore').pipe(fs.createWriteStream('path/to/dest/.gitignore'));
```

**Comment by bajtos** [comment] 2015-02-04 09:33
@superkhau I am afraid your conclusion is not correct. Using `ncp@1.0.1`, I run `bin/ncp` and it copied the hidden files too. The problem must be somewhere else.

**Comment by superkhau** [comment] 2015-02-05 05:44
@bajtos You are right, I wrote a simple test and it does copy over. Will dig deeper.

**Comment by ritch** [comment] 2015-02-05 17:47
Perhap the `.gitignore` file is not included in the package when published to (and installed from) npm?

**Comment by superkhau** [comment] 2015-02-05 18:17
@ritch might be correct. See https://github.com/npm/npm/issues/3763

Will have to dig deeper and see if anyone actually resolved that issue.

**Comment by superkhau** [comment] 2015-02-05 18:50
OK, I'm fairly convinced @ritch is correct. We can reproduce this by inspecting the contents of the tgz generated via `npm pack`

STR
```
cd loopback-workspace
npm pack
tar xvzf loopback-workspace-3.7.0.tgz
ls -la package/templates/components/api-server/template
```

At this step, you should notice the `.gitignore` file has been renamed to `.npmignore`. This tells me its definitely related to the issue I referenced above.

@bajtos @ritch @sam-github Thoughts?

**Comment by sam-github** [comment] 2015-02-05 18:54
@superkhau Horrible. On npm's part. Not sure how to work-around. Can't write the file after-the-fact, you won't have write perms. Perhaps easiest is to PR a fix up to yeoman generator, so it has special copy rules, so `.git_ignore` (or some other name that evades npm's misplaced vigilance) gets copied to `.gitignore`. Or maybe best to point out npm shouldn't mess with files that aren't at the package root!

**Comment by superkhau** [comment] 2015-02-05 19:09
Yeah, the worst part is it does the renaming as part of `npm install` and renames your `.gitignore` to `.npmignore` even if you so some hacks beforehand (ie. `install` script in the `scripts` section). Also, it not only messages with files at the package root, ALL `.gitignore` files down the tree are also renamed.

**Comment by superkhau** [comment] 2015-02-05 19:12
More info on the  `npm install ` renaming here: https://github.com/npm/npm/issues/7252

**Comment by superkhau** [comment] 2015-02-05 21:42
https://github.com/npm/npm/commit/2c6acb96c71c16106965d5cd829b67195dd673c7

**Comment by superkhau** [comment] 2015-02-05 21:45
this might help: https://github.com/yeoman/generator-angular/commit/e8c2c66948a3c8ad3c577b77c061de83cf9acd0d

from https://github.com/yeoman/generator-angular/issues/41

**Comment by superkhau** [comment] 2015-02-06 02:00
I have a solution. We do it like these guys: https://github.com/joshthecoder/ember-cli/commit/676fdcff68a6f468df8c9227ae386c96b46b1a78, but using `fs.renameSync` instead.

Basically they name the file `gitignore` and rename it to `.gitignore` when running the generator. I did a basic test and found that we can also rename the `.npmignore` file directly to `.gitignore`. The caveat is the renaming of the `.gitignore` to `.npmignore` seems to blow away the contents of the file (I need to verify this suspicion). Therefore, there are two solutions I can think of:

1. I rename `.npmignore` to `.gitignore` in `generator-loopback`.
2. I rename the template file in `loopback-workspace` to `gitignore` and then in `generator-loopback` rename `gitignore` to `.gitignore`

:+1: for number 2 as it sounds like a safer option since NPM has no effect on `gitignore` and does nothing to the generated file.

@bajtos @sam-github @ritch

**Comment by superkhau** [comment] 2015-02-06 05:50
https://github.com/strongloop/loopback-workspace/pull/186

**Comment by bajtos** [comment] 2015-02-06 09:46
+1 for the second option, store `.gitignore` under a different name. I don't agree with the particular implementation you have proposed, see my comment in strongloop/loopback-workspace#186.

**Comment by superkhau** [comment] 2015-02-18 01:25
Resolved in strongloop/loopback-workspace#186 and strongloop/generator-loopback#86

**Closed** 2015-02-18 20:24 UTC
Labels: Beginner Friendly, enhancement

**Comment by superkhau** [comment] 2015-02-18 20:27
@sam-github https://github.com/strongloop/generator-loopback/releases/tag/v1.7.2 contains the updates you requested.

**Comment by sam-github** [comment] 2015-02-19 18:18
@superkhau thanks, will speed up committing a loopback app into git
