### ISSUE TITLE
arc manager : Arc UI broken 

### ISSUE THREAD

**Issue by cgole** [strongloop/strong-arc#1009] opened 2015-02-08 17:30 UTC
$ slc arc
Run `npm install loopback-explorer` to enable the LoopBack explorer
Loading workspace /Users/chandrikagole/workspace/testapps/test4
Embedded Process Manager [(none)]:  starting
StrongLoop Arc is running here: http://localhost:54195/#/

http.js:690
    throw new Error('Can\'t set headers after they are sent.');
    ^
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:690:11)
    at ServerResponse.res.setHeader (/usr/local/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/loopback-workspace/node_modules/loopback-explorer/node_modules/express/node_modules/connect/lib/patch.js:134:22)
    at ServerResponse.header (/usr/local/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/express/lib/response.js:717:10)
    at ServerResponse.send (/usr/local/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/express/lib/response.js:146:12)
    at ServerResponse.json (/usr/local/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/express/lib/response.js:235:15)
    at ServerResponse.send (/usr/local/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/express/lib/response.js:134:21)
    at Labeled.<anonymous> (/usr/local/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/strong-mesh-client/proxy/server.js:35:25)
    at Labeled.emit (events.js:95:17)
    at Labeled.<anonymous> (/usr/local/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/strong-mesh-client/node_modules/browserify/node_modules/labeled-stream-splicer/node_modules/stream-splicer/index.js:132:18)
    at Labeled.emit (events.js:117:20)
Chandrikas-MacBook-Air:test4 chandrikagole$ 
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write EPIPE
  at errnoException (net.js:905:11)
  at Object.afterWrite (net.js:721:19)

**Comment by ritch** [comment] 2015-02-08 21:29
This should be fixed now... The issue was caused by a bug introduced in a dependency of browserify (a dependency of strong-mesh-client).

**Comment by chandadharap** [comment] 2015-02-08 21:52
works for me.

**Closed** 2015-02-09 00:18 UTC
Labels: bug, critical

**Comment by chandadharap** [comment] 2015-02-09 02:41
closing. - chanda

**Comment by homeyer** [comment] 2015-02-18 22:54
Has the fix been published to npm? Just saw it occur with:
```
$ npm install -g strongloop
$ slc arc
```

node 0.10.32, npm 2.1.4, slc v2.10.3

**Comment by ritch** [comment] 2015-02-18 23:02
Related... but slightly different. Should be fixed by https://github.com/strongloop/strong-mesh-client/pull/15

**Comment by ritch** [comment] 2015-02-18 23:03
@homeyer see https://github.com/strongloop/strong-arc/issues/1047

**Comment by homeyer** [comment] 2015-02-19 16:06
nice, thanks @ritch!
