### ISSUE TITLE
Arc Metrics view crashes after a while

### ISSUE THREAD

**Issue by seanbrookes** [strongloop/strong-arc#1050] opened 2015-02-19 18:37 UTC
Please triage and reassign to Sean.

**Comment by cgole** [comment] 2015-02-26 00:44
@altsang, can you tell me steps to repro? For me, the chart dont load up consistently and I have "pending data", but I have never seen it crash.

**Comment by cgole** [comment] 2015-02-26 00:44
Also what app do you use for demo?

**Comment by altsang** [comment] 2015-02-26 06:49
steps to reproduce:

I run a local strong-pm instance of loopback-example-app but you can re-create by going to appdemo.strongloop.com:7000 and running Arc from Chrome

see steps below:
1. spin up a strong-pm instance locally - PORT=5000 slc pm -l 7000
2. run `slc strongops --license <license>` in cloned loopback-example-app to enable strong-agent metrics
3. build and deploy loopback-example-app to local strong-pm instance
4. run `PORT=5000 node create-load.js` from bin directory of loopback-example-app to impart load
4. run slc arc
5. load Metrics module
6. open another tab in same window, leave Metrics tab open but not with current focus
7. wait ~10-15 minutes
8. switch BACK to Metrics tab]
9. browser tab will either be blank OR on my Chrome it'll say the page has crashed

**Comment by cgole** [comment] 2015-02-26 19:00
I was able to reproduce this. I had to wait for almost 20 mins before this happened. The metrics page was blank first and then I got the error in the snapshot. -

**Comment by cgole** [comment] 2015-02-26 19:01
![screen shot 2015-02-26 at 10 59 42 am](https://cloud.githubusercontent.com/assets/991632/6399374/cc40c038-bda6-11e4-97c9-d616123660d0.png)

**Comment by chandadharap** [comment] 2015-02-26 21:32
@ijroth still looking to see if this needs to be prioritized as critical or not i think,

**Comment by seanbrookes** [comment] 2015-02-27 16:12
I looked into this a bit and from what I can see it looks like the the metrics aggregation collections are being created as closures so never release for GC.

**Comment by chandadharap** [comment] 2015-02-27 21:39
If this is a memory leak issue, it needs to be fixed, irrespective of Roadmap.

**Comment by chandadharap** [comment] 2015-02-27 21:40
@ritch @seanbrookes

**Comment by altsang** [comment] 2015-03-02 02:42
although folks may not be utilizing our metrics because of considerable friction in getting the key - this is critical for our investor pitches and any due diligence that may ensue.  some of the investors we are talking to have techincal EIRs or are technical themselves and may want to check our offering in more detail.  Intel is already doing so

if we're close to understanding root cause i'd like to understand what it will take to fix

**Comment by altsang** [comment] 2015-03-02 17:49
@chandadharap got it - possibly memory leak, need this fixed depending on LOE

**Comment by seanbrookes** [comment] 2015-03-10 14:43
see PR#1077

**Comment by chandadharap** [comment] 2015-03-11 05:47
@altsang Can you please verify this instead of Chandrika? She is really overloaded and you really need this to work.

**Comment by altsang** [comment] 2015-03-11 06:20
I've pulled master and am testing it overnight

**Comment by chandadharap** [comment] 2015-03-18 04:52
I'm assigning to @altsang since hes already looking at it.

**Comment by altsang** [comment] 2015-03-23 02:00
left it running in background tab for 1 hr, came back to it and the page was frozen, and then finally got the error...

**Comment by sam-github** [comment] 2015-04-01 16:08
@cgole why did you move this into #tbr ?

**Comment by cgole** [comment] 2015-04-01 16:53
I have NO idea how and when I did this!

**Comment by jtary** [comment] 2015-04-07 17:23
@cgole I merged some fixes that should fix this. Can you verify?

**Comment by altsang** [comment] 2015-04-08 00:25
ran for 3 hours as background tab, flipping back and forth only 3 times within the three hours, no crash

**Closed** 2015-04-08 00:26 UTC
Labels: bug, in progress
