### ISSUE TITLE
Cannot run Express app created by Express app generator

### ISSUE THREAD

**Issue by crandmck** [strongloop/strong-arc#1196] opened 2015-04-20 16:29 UTC
The [Express app generator](https://github.com/expressjs/generator) is the "basic / getting started" way we tell people to create a new Express app: http://expressjs.com/starter/generator.html.

However, you cannot run an application created with it using Arc (or `sl-run`) because the requirement is (per Sam):
```
`app` can be a node file to run or a package directory. The default value is
".", the current working directory. Packages will be run by requiring the first
that is found of:
  1. server.js
  2. app.js
  3. `main` property of package.json
  4. index.js
```

See https://github.com/strongloop/strong-supervisor/blob/master/bin/sl-run.txt#L5-L11.

The app that the Express app generator creates does not meet these requirements.  Instead, in `package.json` it has: 
```
 "scripts": {
    "start": "node ./bin/www"
  },
```
The Express docs say to run the app with `npm start`, or `node ./bin/www.

I don't know if we need to fix on our end, change the Express docs, or whether we should open an issue against https://github.com/expressjs/generator, but it seems reasonable to assume that our tools should work with the "default / basic" Express app one way or the other.

**Comment by sam-github** [comment] 2015-05-01 20:45
Duplicate of https://github.com/strongloop-internal/scrum-nodeops/issues/400, I suggest closing this, and trying to get some attention paid to the other. Especially as this bug is against strong-arc.

**Comment by crandmck** [comment] 2015-05-04 16:19
@chandadharap Your call.

**Comment by cgole** [comment] 2015-07-08 21:29
dup for strongloop-internal/scrum-nodeops#400

**Closed** 2015-07-08 21:30 UTC
Labels: bug
