### ISSUE TITLE
slc start: include log output by default for fixed N of lines for now to confirm app is running

### ISSUE THREAD

**Issue by altsang** [strongloop/strong-arc#1117] opened 2015-03-30 21:33 UTC
As a dev user using StrongLoop PM, it would be great if there was some kind of output to know that my app is really running.  Right now you have to type `slc start` and then `slc log-output`.

Can `slc start` include the output that you would've done with `slc log-output`?

Longer term solution would be to really know that the app is really running

**Comment by crandmck** [comment] 2015-03-30 22:27
Without this, then essentially everywhere in the docs where we had 'slc run' that going to replace it with `slc start` (everywhere in the Node Ops docs at least), then we also have to say to do `slc ctl log-dump` to make sure the app is actually running and see errors, etc.

**Comment by altsang** [comment] 2015-03-30 22:45
the generators'  output also need to be changed too for example `slc
loopback`

On Mon, Mar 30, 2015 at 3:27 PM, Rand McKinney <notifications@github.com>
wrote:

> Without this, then essentially everywhere in the docs where we had 'slc
> run' that going to replace it with slc start (everywhere in the Node Ops
> docs at least), then we also have to say to do slc ctl log-dump to make
> sure the app is actually running and see errors, etc.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/strongloop/strong-arc/issues/1117#issuecomment-87859078>
> .
>



-- 
Al Tsang
Co-Founder and CTO @ StrongLoop, Inc.

*StrongLoop <http://strongloop.com/>** makes it easy to **develop APIs
<http://strongloop.com/mobile-application-development/loopback/>** in Node,
plus get DevOps capabilities
<http://strongloop.com/node-js-performance/strongops/> like monitoring,
debugging and clustering**.*

**Comment by chandadharap** [comment] 2015-03-31 05:19
@altsang Is this an Arc issue or were you opening this on strong-pm/nodeops? The reason I ask is, there may be an issue with getting log output if the app did not start correctly in the first place. I think @sam-github had some ideas for future.

**Comment by altsang** [comment] 2015-03-31 06:10
That's the whole point, if the app didn't come up I'm hoping that what is being spit out to the console is what would be made available by doing log-dump, like the infamous EADDRINUSE error. From what I can tell it is.  I've talked to @sam-github  about this already. This has nothing to do with Arc.

Even better is if we can detect that the app isn't running in the first place too.

**Comment by chandadharap** [comment] 2015-03-31 13:38
The issue is under "strong-arc"
Hence the question. I might mirror an issue for detecting app start in the
NodeOps backlog.

-Chanda


On Monday, March 30, 2015, Al Tsang <notifications@github.com> wrote:

> That's the whole point, if the app didn't come up I'm hoping that what is
> being spit out to the console is what would be made available by doing
> log-dump, like the infamous EADDRINUSE error. From what I can tell it is.
> I've talked to @sam-github <https://github.com/sam-github> about this
> already. This has nothing to do with Arc.
>
> Even better is if we can detect that the app isn't running in the first
> place too.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/strongloop/strong-arc/issues/1117#issuecomment-87954792>
> .
>


-- 
Chanda Dharap
Director, Engineering
@StrongLoop Inc
(510) 304-3924
chanda@strongloop.com

*StrongLoop <http://strongloop.com/>** makes it easy to **develop APIs
<http://strongloop.com/mobile-application-development/loopback/>** in Node,
plus get DevOps capabilities
<http://strongloop.com/node-js-performance/strongops/> like monitoring,
debugging and clustering**.*

**Comment by altsang** [comment] 2015-03-31 15:45
ahhh - my bad, I created in the wrong repo thinking that the default in node-ops was the scrum-nodeops repo

@crandmck - I don't think we can mass replace `slc run` with `slc start`.  My opinion is that you only would want to do `slc start` when you are specifically testing under a process manager for things like scale and to get assurance that all is good before deploying to production.  For everyday dev, I think it may make more sense to just do `node <file>.js`  @sam-github pls chime in if you feel differently.

My main concern are folks who don't understand that the process doesn't die unless you tell it to stop after you've done `slc start` blindly following direction and messing up things.  I was able to do that very easily myself when testing :)

**Comment by sam-github** [comment] 2015-03-31 16:50
You only need to use `slc start` for your app if you want it to be controllable (using `slc ctl` or `slc arc`). Otherwise, `node .` works better.

**Comment by sam-github** [comment] 2015-03-31 16:55
@altsang the log dumping behaviour, pls move to scrum-nodeops, where we can discuss for how long slc start should tail the log.

**Comment by chandadharap** [comment] 2015-03-31 17:01
@sam-github @altsang Created here: https://github.com/strongloop-internal/scrum-nodeops/issues/403

Closing this.

**Closed by chandadharap** 2015-03-31 17:01 UTC
Labels: UX
