### ISSUE TITLE
arc manager  :  Load balance loose all pm endpoints, when one of them crashes.

### ISSUE THREAD

**Issue by cgole** [strongloop/strong-arc#1000] opened 2015-02-07 21:33 UTC
To repro - 

I have 2 om servers up an running with an app deployed to them. 
routes.json has 3 entries. 
I kill on of the pm servers. 

Expected : Load balancer should still have the other 2 pm server endpoints.
Actual : LB doesnt have any endpoint. I get a 503: Service Unavailable when I hit the LB url

**Comment by ritch** [comment] 2015-02-07 21:37
Are they still not written when you restart arc?

**Comment by cgole** [comment] 2015-02-07 21:47
Arc restart doesn't fix it.  LB still doesnt have the any pm endpoints. 
When the crashed pm server comes back, the LB starts working again.

**Comment by chandadharap** [comment] 2015-02-08 01:50
@ritch Can you update this with progress? We will need this fixed for Sunday night.

**Comment by ritch** [comment] 2015-02-08 03:50
I wouldn't count on this being resolved by then. Ill update the labels when I take a look tomorrow.

If it is a minor issue I can fix and release tomorrow. First I need to determine the cause which might not be mesh client.

**Comment by ritch** [comment] 2015-02-09 21:07
Fixed in https://github.com/strongloop/strong-mesh-client/pull/14

**Comment by cgole** [comment] 2015-02-26 20:23
verified

**Closed** 2015-02-26 20:29 UTC
Labels: bug
