### ISSUE TITLE
LB box, font text is way too light

### ISSUE THREAD

**Issue by chandadharap** [strongloop/strong-arc#993] opened 2015-02-07 06:49 UTC
It seems to indicate "unavailable" input box. Too light to read.

**Comment by chandadharap** [comment] 2015-02-07 06:51
@altsang Not sure if this is part of a list that Anthony has, so I'll leave it in Planning. Please prioritize if not already. Font is quite unreadable and light.

**Comment by chandadharap** [comment] 2015-02-07 06:52
![light](https://cloud.githubusercontent.com/assets/4267700/6091188/be07e860-ae52-11e4-992a-292870b5f107.jpg)

**Comment by anthonyettinger** [comment] 2015-02-07 07:40
that is the design. its placeholder text. its meant to be muted. I will double check though to be sure something isn't conflicting.

**Comment by altsang** [comment] 2015-02-07 07:43
this is by design as placeholder text as noted by @anthonyettinger, closing

**Closed** 2015-02-07 07:44 UTC
Labels: bug
